version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - CONTAINER_ROLE=web
    depends_on:
      - db
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - CONTAINER_ROLE=worker
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=regulacao_list
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - db
      - redis
    command: php artisan queue:work --sleep=3 --tries=3

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - CONTAINER_ROLE=scheduler
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=regulacao_list
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - db
      - redis
    command: php artisan schedule:work

  vite:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=5173
