[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
