[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[env]
NODE_ENV = "production"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"
